-- select * from dbo.portfolio_summary order by loandate desc

-- Restores the table when the table in UAT has been corrupted.
/*
DELETE FROM [BDE_Data].[dbo].[Portfolio_Summary]
INSERT INTO [BDE_Data].[dbo].[Portfolio_Summary]
           ([Client]
      ,[SortID]
      ,[LoanDate]
      ,[NewLoans]
      ,[Payoffs]
      ,[Active]
      ,[Prepaid or Current]
      ,[Current Month]
      ,[30 Days Delinquent]
      ,[60 Days Delinquent]
      ,[90 Days Delinquent]
      ,[120+ Days Delinquent]
      ,[REO]
      ,[Foreclosure]
      ,[Bankruptcy]
      ,[FHA_PreConveyance]
      ,[Is_EOM]
      ,[LoadDate]
      ,[UPB]
      ,[UPB_NewLoans]
      ,[UPB_Payoffs]
      ,[UPB_Active]
      ,[UPB_Prepaid or Current]
      ,[UPB_Current Month]
      ,[UPB_30 Days Delinquent]
      ,[UPB_60 Days Delinquent]
      ,[UPB_90 Days Delinquent]
      ,[UPB_120+ Days Delinquent]
      ,[UPB_REO]
      ,[UPB_Foreclosure]
      ,[UPB_Bankruptcy]
      ,[UPB_FHA_PreConveyance]
)
SELECT [Client]
      ,[SortID]
      ,[LoanDate]
      ,[NewLoans]
      ,[Payoffs]
      ,[Active]
      ,[Prepaid or Current]
      ,[Current Month]
      ,[30 Days Delinquent]
      ,[60 Days Delinquent]
      ,[90 Days Delinquent]
      ,[120+ Days Delinquent]
      ,[REO]
      ,[Foreclosure]
      ,[Bankruptcy]
      ,[FHA_PreConveyance]
      ,[Is_EOM]
      ,[LoadDate]
      ,[UPB]
      ,[UPB_NewLoans]
      ,[UPB_Payoffs]
      ,[UPB_Active]
      ,[UPB_Prepaid or Current]
      ,[UPB_Current Month]
      ,[UPB_30 Days Delinquent]
      ,[UPB_60 Days Delinquent]
      ,[UPB_90 Days Delinquent]
      ,[UPB_120+ Days Delinquent]
      ,[UPB_REO]
      ,[UPB_Foreclosure]
      ,[UPB_Bankruptcy]
      ,[UPB_FHA_PreConveyance]
  FROM [10.0.3.30].[BDE_Data].[dbo].[Portfolio_Summary]
  --where loandate = '9/29/2017'
  --order by loandate desc
   select * from [Portfolio_Summary] where loandate = '9/29/2017' order by loandate desc


*/

/*   Portfolio_Summary_Investor table

USE [BDE_Data]
GO
DELETE FROM [dbo].[Portfolio_Summary_Investor]
INSERT INTO [dbo].[Portfolio_Summary_Investor]
      ([Client]
      ,[Investor]
      ,[SortID]
      ,[LoanDate]
      ,[NewLoans]
      ,[Payoffs]
      ,[Active]
      ,[Prepaid or Current]
      ,[Current Month]
      ,[30 Days Delinquent]
      ,[60 Days Delinquent]
      ,[90 Days Delinquent]
      ,[120+ Days Delinquent]
      ,[REO]
      ,[Foreclosure]
      ,[Bankruptcy]
      ,[FHA_PreConveyance]
      ,[LoadDate]
      ,[UPB]
      ,[UPB_NewLoans]
      ,[UPB_Payoffs]
      ,[UPB_Active]
      ,[UPB_Prepaid or Current]
      ,[UPB_Current Month]
      ,[UPB_30 Days Delinquent]
      ,[UPB_60 Days Delinquent]
      ,[UPB_90 Days Delinquent]
      ,[UPB_120+ Days Delinquent]
      ,[UPB_REO]
      ,[UPB_Foreclosure]
      ,[UPB_Bankruptcy]
      ,[UPB_FHA_PreConveyance]
		   )

SELECT [Client]
      ,[Investor]
      ,[SortID]
      ,[LoanDate]
      ,[NewLoans]
      ,[Payoffs]
      ,[Active]
      ,[Prepaid or Current]
      ,[Current Month]
      ,[30 Days Delinquent]
      ,[60 Days Delinquent]
      ,[90 Days Delinquent]
      ,[120+ Days Delinquent]
      ,[REO]
      ,[Foreclosure]
      ,[Bankruptcy]
      ,[FHA_PreConveyance]
      ,[LoadDate]
      ,[UPB]
      ,[UPB_NewLoans]
      ,[UPB_Payoffs]
      ,[UPB_Active]
      ,[UPB_Prepaid or Current]
      ,[UPB_Current Month]
      ,[UPB_30 Days Delinquent]
      ,[UPB_60 Days Delinquent]
      ,[UPB_90 Days Delinquent]
      ,[UPB_120+ Days Delinquent]
      ,[UPB_REO]
      ,[UPB_Foreclosure]
      ,[UPB_Bankruptcy]
      ,[UPB_FHA_PreConveyance]
	   FROM [10.0.3.30].[BDE_Data].[dbo].[Portfolio_Summary_Investor]

		    select * from [dbo].[Portfolio_Summary_Investor] --where loandate = '8/31/2015' order by loandate desc
		    select * from [dbo].[Portfolio_Summary] where loandate = '8/31/2015' order by loandate desc



USE [BDESime]
GO
DELETE FROM [dbo].[Portfolio_Summary_Type]
INSERT INTO [dbo].[Portfolio_Summary_Type]
           ([Client]
           ,[Investor]
           ,[LoanType]
           ,[SortID]
           ,[LoanDate]
           ,[NewLoans]
           ,[Payoffs]
           ,[Active]
           ,[Prepaid or Current]
           ,[Current Month]
           ,[30 Days Delinquent]
           ,[60 Days Delinquent]
           ,[90 Days Delinquent]
           ,[120+ Days Delinquent]
           ,[REO]
           ,[Foreclosure]
           ,[Bankruptcy]
           ,[FHA_PreConveyance]
           ,[UPB]
           ,[UPB_NewLoans]
           ,[UPB_Payoffs]
           ,[UPB_Active]
           ,[UPB_Prepaid or Current]
           ,[UPB_Current Month]
           ,[UPB_30 Days Delinquent]
           ,[UPB_60 Days Delinquent]
           ,[UPB_90 Days Delinquent]
           ,[UPB_120+ Days Delinquent]
           ,[UPB_REO]
           ,[UPB_Foreclosure]
           ,[UPB_Bankruptcy]
           ,[UPB_FHA_PreConveyance])
	SELECT  [Client]
           ,[Investor]
           ,[LoanType]
           ,[SortID]
           ,[LoanDate]
           ,[NewLoans]
           ,[Payoffs]
           ,[Active]
           ,[Prepaid or Current]
           ,[Current Month]
           ,[30 Days Delinquent]
           ,[60 Days Delinquent]
           ,[90 Days Delinquent]
           ,[120+ Days Delinquent]
           ,[REO]
           ,[Foreclosure]
           ,[Bankruptcy]
           ,[FHA_PreConveyance]
           ,[UPB]
           ,[UPB_NewLoans]
           ,[UPB_Payoffs]
           ,[UPB_Active]
           ,[UPB_Prepaid or Current]
           ,[UPB_Current Month]
           ,[UPB_30 Days Delinquent]
           ,[UPB_60 Days Delinquent]
           ,[UPB_90 Days Delinquent]
           ,[UPB_120+ Days Delinquent]
           ,[UPB_REO]
           ,[UPB_Foreclosure]
           ,[UPB_Bankruptcy]
           ,[UPB_FHA_PreConveyance]
	   FROM [10.0.3.30].[BDESime].[dbo].[Portfolio_Summary_Type]

SELECT * FROM [BDESime].[dbo].[Portfolio_Summary_Type] order by LoanDate Desc

*/