USE [BDESime]
GO

SET ANSI_PADDING ON
GO
-- select distinct [loan date] FROM [dbo].[delinquency_snapshot] (nolock) 
		   
----/****** Object:  Index [delinquency_snapshot_loan_datecovering]    Script Date: 12/25/2017 11:36:26 AM ******/
----CREATE NONCLUSTERED INDEX [delinquency_snapshot_loan_datecovering] ON [dbo].[delinquency_snapshot]
----(
----	[LOAN DATE] ASC
----)
----INCLUDE ( 	[LOAN NUMBER],
----	[FIRST PRINCIPAL BALANCE],
----	[MTH STATUS NAME],
----	[proper_status]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
----GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [IS_COMPARE_YEAR_IS EOM]    Script Date: 12/25/2017 11:36:26 AM ******/
--CREATE NONCLUSTERED INDEX [IS_COMPARE_YEAR_IS EOM] ON [dbo].[delinquency_snapshot]
--(
--	[IS_COMPARE_YEAR] ASC,
--	[IS EOM] ASC
--)
--INCLUDE ( 	[INVESTOR ID],
--	[MTH STATUS NAME],
--	[LOAN DATE],
--	[iv_cat_cd]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO

--SET ANSI_PADDING ON
--GO

--/****** Object:  Index [IX_Date_UPB]    Script Date: 12/25/2017 11:36:26 AM ******/
--CREATE NONCLUSTERED INDEX [IX_Date_UPB] ON [dbo].[delinquency_snapshot]
--(
--	[LOAN DATE] ASC,
--	[FIRST PRINCIPAL BALANCE] ASC
--)
--INCLUDE ( 	[LOAN NUMBER],
--	[MAN CODE],
--	[MTH STATUS NAME],
--	[IS COMPARE],
--	[owner_name]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO

--SET ANSI_PADDING ON
--GO

--/****** Object:  Index [IX_INVESTOR ID]    Script Date: 12/25/2017 11:36:26 AM ******/
--CREATE NONCLUSTERED INDEX [IX_INVESTOR ID] ON [dbo].[delinquency_snapshot]
--(
--	[INVESTOR ID] ASC,
--	[LOAN DATE] ASC,
--	[iv_cat_cd] ASC,
--	[FIRST PRINCIPAL BALANCE] ASC
--)
--INCLUDE ( 	[LOAN NUMBER],
--	[FIRST P AND I AMOUNT],
--	[SUSPENSE BALANCE],
--	[LOAN LOSS MIT STATUS CODE],
--	[MTH STATUS NAME],
--	[NEXT PAYMENT DUE DATE],
--	[owner_name]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO

--SET ANSI_PADDING ON
--GO

--/****** Object:  Index [IX_INVESTOR ID_iv_cat_cd]    Script Date: 12/25/2017 11:36:26 AM ******/
--CREATE NONCLUSTERED INDEX [IX_INVESTOR ID_iv_cat_cd] ON [dbo].[delinquency_snapshot]
--(
--	[INVESTOR ID] ASC,
--	[iv_cat_cd] ASC,
--	[FIRST PRINCIPAL BALANCE] ASC,
--	[LOAN DATE] ASC
--)
--INCLUDE ( 	[LOAN NUMBER],
--	[MSP DLQ STATUS]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO

--SET ANSI_PADDING ON
--GO

--/****** Object:  Index [IX_IS COMPARE_IS EOM]    Script Date: 12/25/2017 11:36:26 AM ******/
--CREATE NONCLUSTERED INDEX [IX_IS COMPARE_IS EOM] ON [dbo].[delinquency_snapshot]
--(
--	[IS COMPARE] ASC,
--	[IS EOM] ASC
--)
--INCLUDE ( 	[INVESTOR ID],
--	[MTH STATUS NAME],
--	[LOAN DATE],
--	[iv_cat_cd]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO

--SET ANSI_PADDING ON
--GO

--/****** Object:  Index [IX_IS COMPARE_LOAN DATE_UBP]    Script Date: 12/25/2017 11:36:26 AM ******/
--CREATE NONCLUSTERED INDEX [IX_IS COMPARE_LOAN DATE_UBP] ON [dbo].[delinquency_snapshot]
--(
--	[IS COMPARE] ASC,
--	[LOAN DATE] ASC,
--	[FIRST PRINCIPAL BALANCE] ASC
--)
--INCLUDE ( 	[LOAN NUMBER],
--	[MSP DLQ STATUS],
--	[owner_name]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO

--SET ANSI_PADDING ON
--GO

--/****** Object:  Index [IX_IS_COMPARE_LOAN DATE]    Script Date: 12/25/2017 11:36:26 AM ******/
--CREATE NONCLUSTERED INDEX [IX_IS_COMPARE_LOAN DATE] ON [dbo].[delinquency_snapshot]
--(
--	[IS COMPARE] ASC,
--	[LOAN DATE] ASC
--)
--INCLUDE ( 	[LOAN NUMBER],
--	[OLD LOAN NUMBER],
--	[FIRST PRINCIPAL BALANCE],
--	[FIRST P AND I AMOUNT],
--	[SUSPENSE BALANCE],
--	[LOAN LOSS MIT STATUS CODE],
--	[MAN CODE],
--	[MTH STATUS NAME],
--	[NEXT PAYMENT DUE DATE],
--	[CS BORR ORIG CREDIT QLTY CODE],
--	[CS BORR CREDIT QUALITY CODE],
--	[CS BORR CREDIT QUALITY DATE],
--	[NOTE DATE],
--	[SIXTY],
--	[NINETY]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO

--SET ANSI_PADDING ON
--GO

/****** Object:  Index [IX_IS_COMPARE_YEAR]    Script Date: 12/25/2017 11:36:27 AM ******/
--CREATE NONCLUSTERED INDEX [IX_IS_COMPARE_YEAR] ON [dbo].[delinquency_snapshot]
--(
--	[IS_COMPARE_YEAR] ASC
--)
--INCLUDE ( 	[MTH STATUS NAME],
--	[IS EOM],
--	[LOAN DATE]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO

--SET ANSI_PADDING ON
--GO

--/****** Object:  Index [IX_ISCOMPARE]    Script Date: 12/25/2017 11:36:27 AM ******/
--CREATE NONCLUSTERED INDEX [IX_ISCOMPARE] ON [dbo].[delinquency_snapshot]
--(
--	[IS COMPARE] ASC
--)
--INCLUDE ( 	[MTH STATUS NAME],
--	[IS EOM],
--	[LOAN DATE]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO

--/****** Object:  Index [IX_ISCOMPARE_60_90_LOAD]    Script Date: 12/25/2017 11:36:27 AM ******/
--CREATE NONCLUSTERED INDEX [IX_ISCOMPARE_60_90_LOAD] ON [dbo].[delinquency_snapshot]
--(
--	[IS COMPARE] ASC
--)
--INCLUDE ( 	[SIXTY],
--	[NINETY],
--	[LOAN DATE]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO

--SET ANSI_PADDING ON
--GO

--/****** Object:  Index [IX_iv_cat_cd]    Script Date: 12/25/2017 11:36:27 AM ******/
--CREATE NONCLUSTERED INDEX [IX_iv_cat_cd] ON [dbo].[delinquency_snapshot]
--(
--	[INVESTOR ID] ASC,
--	[LOAN DATE] ASC,
--	[iv_cat_cd] ASC,
--	[FIRST PRINCIPAL BALANCE] ASC
--)
--INCLUDE ( 	[LOAN NUMBER],
--	[ARM INDICATOR],
--	[LO TYPE],
--	[MTH STATUS NAME],
--	[proper_status],
--	[owner_name]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO

--SET ANSI_PADDING ON
--GO

--/****** Object:  Index [IX_LOAN DATE_FIRST PRINCIPAL BALANCE]    Script Date: 12/25/2017 11:36:27 AM ******/
--CREATE NONCLUSTERED INDEX [IX_LOAN DATE_FIRST PRINCIPAL BALANCE] ON [dbo].[delinquency_snapshot]
--(
--	[LOAN DATE] ASC,
--	[FIRST PRINCIPAL BALANCE] ASC
--)
--INCLUDE ( 	[LOAN NUMBER],
--	[INVESTOR ID],
--	[ARM INDICATOR],
--	[LO TYPE],
--	[MTH STATUS NAME]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO

--SET ANSI_PADDING ON
--GO

--/****** Object:  Index [IX_LOAN DATE_IS_COMPARE_YEAR]    Script Date: 12/25/2017 11:36:27 AM ******/
--CREATE NONCLUSTERED INDEX [IX_LOAN DATE_IS_COMPARE_YEAR] ON [dbo].[delinquency_snapshot]
--(
--	[LOAN DATE] ASC,
--	[IS_COMPARE_YEAR] ASC
--)
--INCLUDE ( 	[LOAN NUMBER],
--	[INVESTOR ID],
--	[MTH STATUS NAME],
--	[IS EOM],
--	[iv_cat_cd]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--GO

