USE [BDE_Data]
GO
/*
DELETE FROM dbo.portfolio_summary_investor
INSERT INTO [dbo].[Portfolio_Summary_Investor]
           ([Client]
           ,[Investor]
           ,[SortID]
           ,[LoanDate]
           ,[NewLoans]
           ,[Payoffs]
           ,[Active]
           ,[Prepaid or Current]
           ,[pct_prepaid]
           ,[Current Month]
           ,[pct_current]
           ,[30 Days Delinquent]
           ,[pct_30]
           ,[60 Days Delinquent]
           ,[pct_60]
           ,[90 Days Delinquent]
           ,[pct_90]
           ,[120+ Days Delinquent]
           ,[pct_120]
           ,[REO]
           ,[pct_REO]
           ,[Foreclosure]
           ,[pct_Foreclosure]
           ,[Bankruptcy]
           ,[pct_Bankruptcy]
           ,[FHA_PreConveyance]
           ,[pct_FHA_PreConveyance]
           ,[LoadDate])
SELECT [Client]
           ,[Investor]
           ,[SortID]
           ,[LoanDate]
           ,[NewLoans]
           ,[Payoffs]
           ,[Active]
           ,[Prepaid or Current]
           ,[pct_prepaid]
           ,[Current Month]
           ,[pct_current]
           ,[30 Days Delinquent]
           ,[pct_30]
           ,[60 Days Delinquent]
           ,[pct_60]
           ,[90 Days Delinquent]
           ,[pct_90]
           ,[120+ Days Delinquent]
           ,[pct_120]
           ,[REO]
           ,[pct_REO]
           ,[Foreclosure]
           ,[pct_Foreclosure]
           ,[Bankruptcy]
           ,[pct_Bankruptcy]
           ,[FHA_PreConveyance]
           ,[pct_FHA_PreConveyance]
           ,[LoadDate]
  FROM [10.0.3.30].bde_data.dbo.portfolio_summary_investor

SELECT *  FROM [BDE_Data].[dbo].[Portfolio_Summary_Investor]  order by loandate desc
*/

  -- [UAT-SQL01].[bde_data].[dbo].[Holidays]
GO


USE [BDE_Data]
GO
/*
INSERT INTO [dbo].[Portfolio_Summary]
           ([Client]
           ,[SortID]
           ,[LoanDate]
           ,[NewLoans]
           ,[Payoffs]
           ,[Active]
           ,[Prepaid or Current]
           ,[pct_prepaid]
           ,[Current Month]
           ,[pct_current]
           ,[30 Days Delinquent]
           ,[pct_30]
           ,[60 Days Delinquent]
           ,[pct_60]
           ,[90 Days Delinquent]
           ,[pct_90]
           ,[120+ Days Delinquent]
           ,[pct_120]
           ,[REO]
           ,[pct_REO]
           ,[Foreclosure]
           ,[pct_Foreclosure]
           ,[Bankruptcy]
           ,[pct_Bankruptcy]
           ,[FHA_PreConveyance]
           ,[pct_FHA_PreConveyance]
           ,[Is_EOM]
           ,[LoadDate])
SELECT [Client]
      ,[SortID]
      ,[LoanDate]
      ,[NewLoans]
      ,[Payoffs]
      ,[Active]
      ,[Prepaid or Current]
      ,[pct_prepaid]
      ,[Current Month]
      ,[pct_current]
      ,[30 Days Delinquent]
      ,[pct_30]
      ,[60 Days Delinquent]
      ,[pct_60]
      ,[90 Days Delinquent]
      ,[pct_90]
      ,[120+ Days Delinquent]
      ,[pct_120]
      ,[REO]
      ,[pct_REO]
      ,[Foreclosure]
      ,[pct_Foreclosure]
      ,[Bankruptcy]
      ,[pct_Bankruptcy]
      ,[FHA_PreConveyance]
      ,[pct_FHA_PreConveyance]
      ,[Is_EOM]
      ,[LoadDate]
   FROM [10.0.3.30].bde_data.dbo.portfolio_summary

SELECT *  FROM [BDE_Data].[dbo].[Portfolio_Summary]  order by loandate desc
*/